### ISSUE TITLE
CheckUrl on logout, the logout config is not used

### ISSUE THREAD

**Issue by damienalexandre** [BeSimple/BeSimpleSsoAuthBundle#14]
Hi, 
Thx for the great job on this plugin :beer:

I'm having an issue about the logout config. Here is mine:

``` yml
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        my_firewall:
            pattern: ^/
            anonymous: ~
            logout:
                path:   /secured/logout
                target: /
            trusted_sso:
                manager: websso
                login_action: false
                logout_action: false
                login_path: /secured/login
                check_path: /secured/check
                always_use_default_target_path: true
                default_target_path: /
                failure_path: /secured/logout
```

The logout target path is not used. In fact, on logout, it's the check_url path passed to my SSO. So I'm redirected to a 404 page: `http://myserver/secured/check` (without token, I get a 404).

I think the issue is in the Cas Server class:

``` php
class Server extends AbstractServer
{
    /**
     * @return string
     */
    public function getLogoutUrl()
    {
        return sprintf('%s?service=%s', parent::getLogoutUrl(), urlencode($this->getCheckUrl()));
    }
```

As you can see, the "CheckUrl" is used for logout. What I need after a logout is to be redirected to the homepage. 
I don't know neither if the 404 error on my check url is normal, maybe that's the real bug here?
