### ISSUE TITLE
Call to a member function validateCredentials() on a non-object in /webapps/symfony-test/vendor/bundles/BeSimple/SsoAuthBundle/Security/Core/Authentication/Token/SsoToken.php on line 39

### ISSUE THREAD

**Issue by david42** [BeSimple/BeSimpleSsoAuthBundle#16]
Hi,

I installed this bundle.

My security.yml :
security:

```
factories:
    - "%kernel.root_dir%/../vendor/bundles/BeSimple/SsoAuthBundle/Resources/config/security_factories.xml"
encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    dav2\TestBundle\Entity\User: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    #in_memory:
    #    users:
    #        user:  { password: userpass, roles: [ 'ROLE_USER' ] }
    #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    user_db:
        entity: { class: dav2\TestBundle\Entity\User, property: username }

  firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false



    my_firewall:
        pattern: ^/
        trusted_sso:
            manager: my_manager
            login_action: false
            logout_action: false

access_control:
    - { path: ^/crud, roles: ROLE_ADMIN }
```

I have this error with URL ^/crud (access_control), the other URL are ok.
If I use the provider "in-memory" and not "user_db", I don't have this problem.

Thanks for your help.
