### ISSUE TITLE
Is this bundle still alive ? Redirect to login page after serviceValidate

### ISSUE THREAD

**Issue by youknowriad** [BeSimple/BeSimpleSsoAuthBundle#32]
Hello,

I'm trying to make this bundle work with SF 2.1, but can't. my configuration is something like this

```
security:
    firewalls:
        secured:
            pattern: ^/secured/.*$
            trusted_sso:
                manager: admin_sso
                login_action: false
                logout_action: false
                create_users: true
                created_users_roles: [ROLE_USER, ROLE_ADMIN]
                check_path: /secured/login_check
                login_path: /login

be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: http://localhost:8888/login
            logout_url: http://localhost:8888/logout
            validation_url: http://localhost:8888/serviceValidate
```

but i'm redirected to login page after login success in my cas server. is there a chance to make this bundle work or is there any alternatives ?

Thanks.
