### ISSUE TITLE
Too many redirections

### ISSUE THREAD

**Issue by modlew** [BeSimple/BeSimpleSsoAuthBundle#34]
Hi everyone.

I just setup symfony and this bundle, I tried to configure it but it seems I am doing something wrong.

my security.yml contains :

```
    my_firewall:
        pattern: ^/
        trusted_sso:
            manager: admin_sso
            create_users: false
            login_action: false
            logout_action: false
            login_path: /login
            check_path: /login_check
```

my routing.yml contains :

```
    login:
        pattern:   /login

    login_check:
        pattern:   /login_check
```

and my config.yml contains :

```
    be_simple_sso_auth:
        admin_sso:
            protocol:
                id: cas
                version: 2
        server:
                id: cas
                login_url: https://cas.*.fr/login
                logout_url: https://cas.*.fr/logout
                validation_url: https://cas.*.fr/serviceValidate
```

So as defined in my security.yml, as soon as I try to browse my application, I am redirected to my cas login url, this is perfect. Anyway, when I login or when I am already logged, I have an error from my browser because of too many redirections :

```
    cas login --> sf login_check --> sf login --> cas login ...
```

Thank you in advance for any help you can provide me !
