### ISSUE TITLE
User reloaded on Logout page

### ISSUE THREAD

**Issue by vladicov** [BeSimple/BeSimpleSsoAuthBundle#36]
Hey, great bundle!

I am using this bundle successfully, but I am having trouble configuring the logout page.

I am trying to use the built in functionality to intercept login/logout requests but the logout portion seems to function incorrectly.  When a user accesses a logout link in our application, they are brought to the logout redirect page, but all of the user data is still refreshed from our user provider.  Symfony shows the user as unauthenticated in the profiler.  If the logout page is refreshed, the user data is no longer reloaded and the token is gone. We are loading our user data from an oracle database using doctrine after SSO authentication.  Here is my firewall config:
# security.yml

```
providers:
    db_users:
        entity: { class: MyCoreBundle:MyUser}

firewalls:
    dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false

    login:
        pattern:  ^/login$
        security: false

    firewall:
        pattern: ^/
        trusted_sso:
            manager: my_sso
            login_action: MyCoreBundle:SsoLogin:login
            logout_action: MyCoreBundle:SsoLogin:logout
            login_path: /login
            check_path: /login_check
        logout: true
```

I can post our User entity and UserProvider, but they are very basic, taken from all the examples.  My login/logout actions are different cause we are overriding your controller.
