### ISSUE TITLE
Configuration option "login_path" is not used

### ISSUE THREAD

**Issue by adrienlucas** [BeSimple/BeSimpleSsoAuthBundle#57]
According to the documentation : 

> `login_path`: path to redirect to when login needed.

It seems that it is actually not used by the bundle...
At least, setting it doesn't produce any effect.

Here is a sample of my app/config/security.yml (in case i just didn't get it): 

``` YAML
security:
    #...
    firewalls:
        #...
        secured_area:
            switch_user: true
            anonymous: ~
            pattern:    ^/
            form_login:
                login_path: extranet_login
                check_path: extranet_security_check
            logout:
                path:   extranet_logout
                target: extranet_login
            http_basic:
                realm: "Espace Prive"
            trusted_sso:
                manager: my_cas
                login_path: /login
                check_path: /login_check
                login_action: ExtranetBundle:Default:login
                logout_action: ExtranetBundle:Default:logout
                create_users: false
                created_users_roles: [ROLE_USER]
```

Can someone enlighten this out please?
