### ISSUE TITLE
Login check, login

### ISSUE THREAD

**Issue by ghost** [BeSimple/BeSimpleSsoAuthBundle#60]
Hello,
i'm newbie with symfony 2 and i'm currently trying to use ssoauth bundle. I have few problems : first when i try to go on one of my webpages, a box tells me : 
"An error occurred while loading the web debug toolbar (500: Internal Server Error).
Do you want to open the profiler?"
If I click on Cancel button, the box disappears. Then, every webpages are replace with this text : 
"You need to authenticate
A Token was not found in the SecurityContext.
Follow this link to authenticate with external server : https://xxx.fr/xxx-cas-server/login?service=xxxx"

I click on the link, i log in but then symfony goes to app_dev/login_check which is a totally blank page. 

What should I do to don't see the box error again ? And why it doesn't redirect me to the webpage I asked first instead of a blank page ?
Here is my config : 
# security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

```
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

providers:
    in_memory:
        memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


firewalls:
    my_firewall:
        trusted_sso:
            manager: admin_sso
            login_action: BeSimpleSsoAuthBundle:TrustedSso:login
            logout_action: BeSimpleSsoAuthBundle:TrustedSso:logout
            create_users: true
            created_users_roles: [ROLE_USER, ROLE_ADMIN]

access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
```
# routing.yml

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern: /login
logout:
    pattern: /logout
login_check:
    pattern:   /login_check
# config.yml

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
# Twig Configuration

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Assetic Configuration

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
# Doctrine Configuration

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

```
orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true
```
# Swiftmailer Configuration

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
be_simple_sso_auth: 
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: https://xxx.fr/xxxx-cas-server/login
            logout_url: https://xxx.fr/xxx-cas-server/logout
            validation_url: https://xxxx.fr/xx-cas-server/serviceValidate

Thank you.
